# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Flagstaff Trail Faeries
email: admiral.rockbar@flagstafftrailfaeries.com
description: > # this means to ignore newlines until "baseurl:"
  The Flagstaff Trail Faeries is a group of dedicated trail users, willing to put their time
  where their mouth is, and build the trails they use.
baseurl: "/flagstafftrailfaeries" # the subpath of your site, e.g. /blog
url: "https://exegete46.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Plugins, yay!
gems:
  # Creates an XML sitemap.
  - jekyll-sitemap
  # Compile Coffeescript to Javascript.
  - jekyll-coffeescript
  # Compile all of the assets together.
  - jekyll-assets

assets:
  # Add a CDN for where to host static files.
  # cdn: "http://yourdomain.com"
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - LICENSE
  - README.md
  - server.sh
  - aliases
